/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HackathonIdRouteImport } from './routes/hackathon.$id'
import { Route as SubmitRouteImport } from './routes/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonIdRoute = HackathonIdRouteImport.update({
  id: '/hackathon/$id',
  path: '/hackathon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hackathon/$id': typeof HackathonIdRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hackathon/$id': typeof HackathonIdRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hackathon/$id': typeof HackathonIdRoute
  '/submit': typeof SubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hackathon/$id' | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hackathon/$id' | '/submit'
  id: '__root__' | '/' | '/hackathon/$id' | '/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HackathonIdRoute: typeof HackathonIdRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon/$id': {
      id: '/hackathon/$id'
      path: '/hackathon/$id'
      fullPath: '/hackathon/$id'
      preLoaderRoute: typeof HackathonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HackathonIdRoute: HackathonIdRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
